# Amazon Customer Review Clustering and Topic Modeling

*In* this project, we use unsupervised learning models to cluster unlabeled documents into different groups, visualize the results and identify their latent topics/structures.

## Contents

* [Part 1: Load Data](#Part-1:-Load-Data)
* [Part 2: Tokenizing and Stemming](#Part-2:-Tokenizing-and-Stemming)
* [Part 3: TF-IDF](#Part-3:-TF-IDF)
* [Part 4: K-means clustering](#Part-4:-K-means-clustering)
* [Part 5: Topic Modeling - Latent Dirichlet Allocation](#Part-5:-Topic-Modeling---Latent-Dirichlet-Allocation)


# Part 0: Setup Google Drive Environment

In [ ]:
!pip install -U -q PyDrive

from pydrive.auth import GoogleAuth
from pydrive.drive import GoogleDrive
from google.colab import auth
from oauth2client.client import GoogleCredentials

auth.authenticate_user()
gauth = GoogleAuth()
gauth.credentials = GoogleCredentials.get_application_default()
drive = GoogleDrive(gauth)

In [ ]:
#https://drive.google.com/open?id=1kbIpSXq9tqwXlab096WZLPCRdAfXjbBp
file = drive.CreateFile({'id':'1kbIpSXq9tqwXlab096WZLPCRdAfXjbBp'}) 
file.GetContentFile('data.tsv')  

# Part 1: Load Data

In [ ]:
import numpy as np
import pandas as pd
import nltk

import gensim
import re

from sklearn.feature_extraction.text import TfidfVectorizer
import matplotlib.pyplot as plt

nltk.download('punkt')
nltk.download('stopwords')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


True

In [ ]:
# Load data into dataframe
df = pd.read_csv('data.tsv', sep='\t', header=0, error_bad_lines=False)

b'Skipping line 8704: expected 15 fields, saw 22\nSkipping line 16933: expected 15 fields, saw 22\nSkipping line 23726: expected 15 fields, saw 22\n'
b'Skipping line 85637: expected 15 fields, saw 22\n'
b'Skipping line 132136: expected 15 fields, saw 22\nSkipping line 158070: expected 15 fields, saw 22\nSkipping line 166007: expected 15 fields, saw 22\nSkipping line 171877: expected 15 fields, saw 22\nSkipping line 177756: expected 15 fields, saw 22\nSkipping line 181773: expected 15 fields, saw 22\nSkipping line 191085: expected 15 fields, saw 22\nSkipping line 196273: expected 15 fields, saw 22\nSkipping line 196331: expected 15 fields, saw 22\n'
b'Skipping line 197000: expected 15 fields, saw 22\nSkipping line 197011: expected 15 fields, saw 22\nSkipping line 197432: expected 15 fields, saw 22\nSkipping line 208016: expected 15 fields, saw 22\nSkipping line 214110: expected 15 fields, saw 22\nSkipping line 244328: expected 15 fields, saw 22\nSkipping line 248519: expected 15 fields,

In [ ]:
df.head()

marketplace  ...  review_date
0          US  ...   2015-08-31
1          US  ...   2015-08-31
2          US  ...   2015-08-31
3          US  ...   2015-08-31
4          US  ...   2015-08-31

[5 rows x 15 columns]

In [ ]:
# Remove missing value
df.review_body.dropna(inplace=True)

In [ ]:
df.shape

(960204, 15)

In [ ]:
# use the first 1000 data as our training data
data = df.loc[:50000, 'review_body'].tolist()

# Part 2: Tokenizing and Stemming

Load stopwords and stemmer function from NLTK library.
Stop words are words like "a", "the", or "in" which don't convey significant meaning.
Stemming is the process of breaking a word down into its root.

In [ ]:
# Use nltk's English stopwords.
stopwords = nltk.corpus.stopwords.words('english')

print ("We use " + str(len(stopwords)) + " stop-words from nltk library.")
print (stopwords[:10])

We use 179 stop-words from nltk library.
['i', 'me', 'my', 'myself', 'we', 'our', 'ours', 'ourselves', 'you', "you're"]


In [ ]:
from nltk.stem.snowball import SnowballStemmer
stemmer = SnowballStemmer("english")

# tokenization and stemming
def tokenization_and_stemming(text):
    # exclude stop words and tokenize the document, generate a list of string 
    tokens = [word.lower() for word in nltk.word_tokenize(text) if word not in stopwords]

    filtered_tokens = []
    
    # filter out any tokens not containing letters (e.g., numeric tokens, raw punctuation)
    for token in tokens:
        if re.search('[a-zA-Z]', token):
            filtered_tokens.append(token)
            
    # stemming
    stems = [stemmer.stem(t) for t in filtered_tokens]
    return stems

# tokenization without stemming
def tokenization(text):
    tokens = [word.lower() for sent in nltk.sent_tokenize(text) for word in nltk.word_tokenize(sent) if word not in stopwords]
    filtered_tokens = []
    for token in tokens:
        if re.search('[a-zA-Z]', token):
            filtered_tokens.append(token)
    return filtered_tokens

In [ ]:
# tokenization and stemming
tokenization_and_stemming(data[0])

['absolut',
 'love',
 'watch',
 'get',
 'compliment',
 'almost',
 'everi',
 'time',
 'i',
 'wear',
 'dainti']

Use our defined functions to analyze (i.e. tokenize, stem) our reviews.

In [ ]:
# 1. do tokenization and stemming for all the documents
# 2. also just do tokenization for all the documents
# the goal is to create a mapping from stemmed words to original tokenized words for result interpretation.
docs_stemmed = []
docs_tokenized = []
for i in data:
    tokenized_and_stemmed_results = tokenization_and_stemming(i)
    docs_stemmed.extend(tokenized_and_stemmed_results)
    
    tokenized_results = tokenization(i)
    docs_tokenized.extend(tokenized_results)

In [ ]:
# create a mapping from stemmed words to original words
vocab_frame_dict = {docs_stemmed[x]:docs_tokenized[x] for x in range(len(docs_stemmed))}

# Part 3: TF-IDF

TF: Term Frequency

IDF: Inverse Document Frequency

***example:***

document1: "Yujing with Song"

document 2: "Yujing with with Song"

document1: tf-idf [1, 0.5, 0.5, 0];  document2: tf-idf [0, 1, 0.5, 1]  

2-gram: 

document 1: Yujing with with Song; document 2: Yujing with with with with Song

3-gram:

document 1: Yujing with Song;  document 2: Yujing with with, with with Song


In [ ]:
# define vectorizer parameters
# TfidfVectorizer will help us to create tf-idf matrix
# max_df : maximum document frequency for the given word
# min_df : minimum document frequency for the given word
# max_features: maximum number of words
# use_idf: if not true, we only calculate tf
# stop_words : built-in stop words
# tokenizer: how to tokenize the document
# ngram_range: (min_value, max_value), eg. (1, 3) means the result will include 1-gram, 2-gram, 3-gram
tfidf_model = TfidfVectorizer(max_df=0.99, max_features=1000,
                                 min_df=0.01, stop_words='english',
                                 use_idf=True, tokenizer=tokenization_and_stemming, ngram_range=(1,2))

tfidf_matrix = tfidf_model.fit_transform(data) #fit the vectorizer to synopses

print ("In total, there are " + str(tfidf_matrix.shape[0]) + \
      " reviews and " + str(tfidf_matrix.shape[1]) + " terms.")

/usr/local/lib/python3.6/dist-packages/sklearn/feature_extraction/text.py:385: UserWarning: Your stop_words may be inconsistent with your preprocessing. Tokenizing the stop words generated tokens ['afterward', 'alon', 'alreadi', 'alway', 'anoth', 'anyon', 'anyth', 'anywher', 'becam', 'becom', 'besid', 'cri', 'describ', 'els', 'elsewher', 'empti', 'everi', 'everyon', 'everyth', 'everywher', 'fifti', 'forti', 'henc', 'hereaft', 'herebi', 'howev', 'hundr', 'inde', 'mani', 'meanwhil', 'moreov', 'nobodi', 'noon', 'noth', 'nowher', 'otherwis', 'perhap', 'pleas', 'sever', 'sinc', 'sincer', 'sixti', 'someon', 'someth', 'sometim', 'somewher', 'thenc', 'thereaft', 'therebi', 'therefor', 'togeth', 'twelv', 'twenti', 'whatev', 'whenc', 'whenev', 'wherea', 'whereaft', 'wherebi', 'wherev'] not in stop_words.
  'stop_words.' % sorted(inconsistent))


In total, there are 1000 reviews and 291 terms.


In [ ]:
# check the parameters
tfidf_model.get_params()

{'analyzer': 'word',
 'binary': False,
 'decode_error': 'strict',
 'dtype': numpy.float64,
 'encoding': 'utf-8',
 'input': 'content',
 'lowercase': True,
 'max_df': 0.99,
 'max_features': 1000,
 'min_df': 0.01,
 'ngram_range': (1, 2),
 'norm': 'l2',
 'preprocessor': None,
 'smooth_idf': True,
 'stop_words': 'english',
 'strip_accents': None,
 'sublinear_tf': False,
 'token_pattern': '(?u)\\b\\w\\w+\\b',
 'tokenizer': <function __main__.tokenization_and_stemming>,
 'use_idf': True,
 'vocabulary': None}

Save the terms identified by TF-IDF.

In [ ]:
# words
tf_selected_words = tfidf_model.get_feature_names()

In [ ]:
# print out words
tf_selected_words[:10]

["'m",
 "'s",
 "'s watch",
 'abl',
 'absolut',
 'absolut love',
 'accur',
 'actual',
 'adjust',
 'alarm']

# Part 4: K-means clustering

In [ ]:
# k-means clustering
from sklearn.cluster import KMeans

num_clusters = 5

# number of clusters
km = KMeans(n_clusters=5)
km.fit(tfidf_matrix)

clusters = km.labels_.tolist()

In [ ]:
clusters

[1,
 1,
 2,
 2,
 2,
 1,
 3,
 2,
 3,
 2,
 2,
 2,
 2,
 2,
 3,
 2,
 2,
 2,
 4,
 2,
 2,
 3,
 2,
 2,
 2,
 2,
 4,
 2,
 3,
 2,
 2,
 0,
 2,
 2,
 2,
 1,
 2,
 2,
 1,
 2,
 2,
 2,
 2,
 1,
 1,
 1,
 2,
 2,
 2,
 2,
 2,
 2,
 4,
 2,
 2,
 0,
 1,
 2,
 1,
 2,
 2,
 1,
 2,
 2,
 1,
 2,
 2,
 2,
 2,
 1,
 2,
 3,
 2,
 2,
 2,
 0,
 2,
 0,
 2,
 1,
 1,
 2,
 2,
 2,
 2,
 2,
 3,
 2,
 1,
 2,
 2,
 2,
 2,
 0,
 0,
 0,
 2,
 3,
 2,
 2,
 2,
 2,
 2,
 1,
 2,
 2,
 2,
 2,
 0,
 3,
 2,
 2,
 1,
 0,
 2,
 2,
 2,
 2,
 2,
 0,
 2,
 2,
 2,
 2,
 1,
 2,
 1,
 2,
 2,
 3,
 2,
 2,
 2,
 4,
 2,
 1,
 2,
 2,
 2,
 2,
 2,
 2,
 3,
 4,
 3,
 2,
 2,
 2,
 2,
 0,
 2,
 2,
 2,
 3,
 0,
 2,
 2,
 2,
 2,
 2,
 2,
 3,
 2,
 0,
 1,
 1,
 4,
 2,
 2,
 0,
 2,
 0,
 2,
 1,
 2,
 2,
 3,
 2,
 2,
 4,
 2,
 4,
 2,
 4,
 1,
 0,
 2,
 3,
 2,
 2,
 3,
 2,
 1,
 2,
 0,
 2,
 2,
 2,
 2,
 3,
 2,
 1,
 0,
 2,
 0,
 4,
 2,
 2,
 2,
 2,
 2,
 1,
 0,
 4,
 2,
 2,
 1,
 2,
 2,
 2,
 2,
 2,
 2,
 3,
 2,
 2,
 2,
 4,
 2,
 0,
 2,
 3,
 2,
 2,
 4,
 0,
 2,
 3,
 2,
 4,
 2,
 2,
 3,
 2,
 2,
 2,
 3,
 4,
 2,
 2,


In [ ]:
tfidf_matrix

<1000x291 sparse matrix of type '<class 'numpy.float64'>'
	with 8591 stored elements in Compressed Sparse Row format>

## 4.1. Analyze K-means Result

In [ ]:
# create DataFrame films from all of the input files.
product = { 'review': df[:1000].product_title, 'cluster': clusters}
frame = pd.DataFrame(product, columns = ['review', 'cluster'])

In [ ]:
frame.head(10)

review  cluster
0  Invicta Women's 15150 "Angel" 18k Yellow Gold ...        2
1  Kenneth Cole New York Women's KC4944 Automatic...        2
2  Ritche 22mm Black Stainless Steel Bracelet Wat...        4
3  Citizen Men's BM8180-03E Eco-Drive Stainless S...        4
4  Orient ER27009B Men's Symphony Automatic Stain...        4
5  Casio Men's GW-9400BJ-1JF G-Shock Master of G ...        2
6  Fossil Women's ES3851 Urban Traveler Multifunc...        3
7  INFANTRY Mens Night Vision Analog Quartz Wrist...        4
8                     G-Shock Men's Grey Sport Watch        4
9          Heiden Quad Watch Winder in Black Leather        4

In [ ]:
print ("Number of reviews included in each cluster:")
frame['cluster'].value_counts().to_frame()

Number of reviews included in each cluster:


cluster
2      663
1      109
3       90
0       70
4       68

In [ ]:
km.cluster_centers_

array([[0.        , 0.01363025, 0.        , ..., 0.        , 0.00618662,
        0.        ],
       [0.        , 0.03973094, 0.        , ..., 0.        , 0.00864147,
        0.        ],
       [0.00488169, 0.03875878, 0.        , ..., 0.01009617, 0.01230684,
        0.00485266],
       [0.        , 0.00958672, 0.        , ..., 0.00278628, 0.        ,
        0.01814849],
       [0.01285187, 0.0451203 , 0.00387628, ..., 0.00609378, 0.01581687,
        0.01249144]])

# Part 5: Topic Modeling - Latent Dirichlet Allocation

In [ ]:
# Use LDA for clustering
from sklearn.decomposition import LatentDirichletAllocation
lda = LatentDirichletAllocation(n_components=500)

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer
# LDA requires integer values
tfidf_model_lda = CountVectorizer(max_df=0.99, max_features=500,
                                 min_df=0.01, stop_words='english',
                                 tokenizer=tokenization_and_stemming, ngram_range=(1,1))

tfidf_matrix_lda = tfidf_model_lda.fit_transform(data) #fit the vectorizer to synopses

print ("In total, there are " + str(tfidf_matrix_lda.shape[0]) + \
      " reviews and " + str(tfidf_matrix_lda.shape[1]) + " terms.")

/usr/local/lib/python3.6/dist-packages/sklearn/feature_extraction/text.py:385: UserWarning: Your stop_words may be inconsistent with your preprocessing. Tokenizing the stop words generated tokens ['afterward', 'alon', 'alreadi', 'alway', 'anoth', 'anyon', 'anyth', 'anywher', 'becam', 'becom', 'besid', 'cri', 'describ', 'els', 'elsewher', 'empti', 'everi', 'everyon', 'everyth', 'everywher', 'fifti', 'forti', 'henc', 'hereaft', 'herebi', 'howev', 'hundr', 'inde', 'mani', 'meanwhil', 'moreov', 'nobodi', 'noon', 'noth', 'nowher', 'otherwis', 'perhap', 'pleas', 'sever', 'sinc', 'sincer', 'sixti', 'someon', 'someth', 'sometim', 'somewher', 'thenc', 'thereaft', 'therebi', 'therefor', 'togeth', 'twelv', 'twenti', 'whatev', 'whenc', 'whenev', 'wherea', 'whereaft', 'wherebi', 'wherev'] not in stop_words.
  'stop_words.' % sorted(inconsistent))


In total, there are 1000 reviews and 245 terms.


In [ ]:
# document topic matrix for tfidf_matrix_lda
lda_output = lda.fit_transform(tfidf_matrix_lda)
print(lda_output.shape)
print(lda_output)

(1000, 500)
[[0.00025    0.00025    0.00025    ... 0.00025    0.00025    0.00025   ]
 [0.0005     0.0005     0.0005     ... 0.0005     0.0005     0.0005    ]
 [0.002      0.002      0.002      ... 0.002      0.002      0.002     ]
 ...
 [0.001      0.001      0.001      ... 0.001      0.001      0.001     ]
 [0.0005     0.0005     0.0005     ... 0.0005     0.0005     0.0005    ]
 [0.00033333 0.00033333 0.00033333 ... 0.00033333 0.00033333 0.00033333]]


In [ ]:
# topics and words matrix
topic_word = lda.components_
print(topic_word.shape)
print(topic_word)

(500, 245)
[[0.002 0.002 0.002 ... 0.002 0.002 0.002]
 [0.002 0.002 0.002 ... 0.002 0.002 0.002]
 [0.002 0.002 0.002 ... 0.002 0.002 0.002]
 ...
 [0.002 0.002 0.002 ... 0.002 0.002 0.002]
 [0.002 0.002 0.002 ... 0.002 0.002 0.002]
 [0.002 0.002 0.002 ... 0.002 0.002 0.002]]


In [ ]:
# column names
topic_names = ["Topic" + str(i) for i in range(lda.n_components)]

# index names
doc_names = ["Doc" + str(i) for i in range(len(data))]

df_document_topic = pd.DataFrame(np.round(lda_output, 2), columns=topic_names, index=doc_names)

# get dominant topic for each document
topic = np.argmax(df_document_topic.values, axis=1)
df_document_topic['topic'] = topic

df_document_topic.head(10)

Topic0  Topic1  Topic2  Topic3  ...  Topic497  Topic498  Topic499  topic
Doc0     0.0     0.0     0.0     0.0  ...       0.0       0.0       0.0    398
Doc1     0.0     0.0     0.0     0.0  ...       0.0       0.0       0.0     31
Doc2     0.0     0.0     0.0     0.0  ...       0.0       0.0       0.0      0
Doc3     0.0     0.0     0.0     0.0  ...       0.0       0.0       0.0    176
Doc4     0.0     0.0     0.0     0.0  ...       0.0       0.0       0.0    381
Doc5     0.0     0.0     0.0     0.0  ...       0.0       0.0       0.0     50
Doc6     0.0     0.0     0.0     0.0  ...       0.0       0.0       0.0     25
Doc7     0.0     0.0     0.0     0.0  ...       0.0       0.0       0.0    251
Doc8     0.0     0.0     0.0     0.0  ...       0.0       0.0       0.0    177
Doc9     0.0     0.0     0.0     0.0  ...       0.0       0.0       0.0      5

[10 rows x 501 columns]

In [ ]:
df_document_topic['topic'].value_counts().to_frame()

topic
82      53
31      48
447     45
177     40
281     24
..     ...
143      1
351      1
350      1
150      1
262      1

[228 rows x 1 columns]

In [ ]:
# topic word matrix
print(lda.components_)
# topic-word matrix
df_topic_words = pd.DataFrame(lda.components_)

# column and index
df_topic_words.columns = tfidf_model_lda.get_feature_names()
df_topic_words.index = topic_names

df_topic_words.head()

[[0.002 0.002 0.002 ... 0.002 0.002 0.002]
 [0.002 0.002 0.002 ... 0.002 0.002 0.002]
 [0.002 0.002 0.002 ... 0.002 0.002 0.002]
 ...
 [0.002 0.002 0.002 ... 0.002 0.002 0.002]
 [0.002 0.002 0.002 ... 0.002 0.002 0.002]
 [0.002 0.002 0.002 ... 0.002 0.002 0.002]]


'm     's    abl  absolut  accur  ...   work   worn  worth  wrist   year
Topic0  0.002  0.002  0.002    0.002  0.002  ...  0.002  0.002  0.002  0.002  0.002
Topic1  0.002  0.002  0.002    0.002  0.002  ...  0.002  0.002  0.002  0.002  0.002
Topic2  0.002  0.002  0.002    0.002  0.002  ...  0.002  0.002  0.002  0.002  0.002
Topic3  0.002  0.002  0.002    0.002  0.002  ...  0.002  0.002  0.002  0.002  0.002
Topic4  0.002  0.002  0.002    0.002  0.002  ...  0.002  0.002  0.002  0.002  0.002

[5 rows x 245 columns]

In [ ]:
# print top n keywords for each topic
def print_topic_words(tfidf_model, lda_model, n_words):
    words = np.array(tfidf_model.get_feature_names())
    topic_words = []
    # for each topic, we have words weight
    for topic_words_weights in lda_model.components_:
        top_words = topic_words_weights.argsort()[::-1][:n_words]
        topic_words.append(words.take(top_words))
    return topic_words

topic_keywords = print_topic_words(tfidf_model=tfidf_model_lda, lda_model=lda, n_words=15)        

df_topic_words = pd.DataFrame(topic_keywords)
df_topic_words.columns = ['Word '+str(i) for i in range(df_topic_words.shape[1])]
df_topic_words.index = ['Topic '+str(i) for i in range(df_topic_words.shape[0])]
df_topic_words

Word 0 Word 1 Word 2   Word 3  ... Word 11 Word 12 Word 13 Word 14
Topic 0     year   gave    fit   finish  ...    face  expens  expect   excel
Topic 1     year   gave    fit   finish  ...    face  expens  expect   excel
Topic 2     year   gave    fit   finish  ...    face  expens  expect   excel
Topic 3     year   gave    fit   finish  ...    face  expens  expect   excel
Topic 4     year   gave    fit   finish  ...    face  expens  expect   excel
...          ...    ...    ...      ...  ...     ...     ...     ...     ...
Topic 495   year   gave    fit   finish  ...    face  expens  expect   excel
Topic 496   gold   larg   good  purchas  ...  number  amazon   metal    wear
Topic 497   year   gave    fit   finish  ...    face  expens  expect   excel
Topic 498   year   gave    fit   finish  ...    face  expens  expect   excel
Topic 499   year   gave    fit   finish  ...    face  expens  expect   excel

[500 rows x 15 columns]